#
# Cache management utilities for opah
#
# Provides functions for reading, writing, and managing the secrets cache.
# The cache uses a tab-separated data format (not executable code) with
# escaped values for security and correctness.
#
# Cache format: KEY<tab>ESCAPED_VALUE
# where ESCAPED_VALUE is generated by `string escape --style=script`
#

#
# Read cache and export secrets as environment variables
#
# Reads the cache file and exports each secret as a global environment variable.
# Returns the number of secrets loaded.
#
# @param cache_file The path to the cache file
# @return The number of secrets successfully loaded (stdout), 0 on success, 1 on error
#
function _opah_cache_read -d "Read cache and export secrets to environment"
    set -l cache_file $argv[1]
    
    if not test -f "$cache_file"
        return 1
    end
    
    set -l count 0
    
    while read -l line
        # Skip comments and empty lines
        if string match -qr '^\s*(#|$)' "$line"
            continue
        end
        
        # Parse tab-separated key-value pairs (split at most once to preserve tabs in values)
        set -l parts (string split -m 1 \t "$line")

        if test (count $parts) -ge 2
            set -l key $parts[1]
            set -l escaped_value $parts[2]
            
            # Unescape the value safely
            set -l value (string unescape --style=script "$escaped_value")
            
            # Export as global environment variable
            set -gx $key "$value"
            set count (math $count + 1)
        end
    end <"$cache_file"
    
    echo $count
    return 0
end

#
# Write secrets to cache atomically
#
# Writes secrets to a temporary file then atomically moves it to the cache location.
# Uses secure permissions (600) and string escape for safe serialization.
#
# @param cache_file The path to the cache file
# @param secrets_stream Tab-separated KEY<tab>VALUE stream from stdin
# @return 0 on success, 1 on error
#
function _opah_cache_write -d "Write secrets to cache atomically"
    set -l cache_file $argv[1]
    set -l cache_dir (dirname "$cache_file")
    
    # Create cache directory if needed
    mkdir -p "$cache_dir"
    
    # Create temp file with secure permissions
    set -l temp_cache (mktemp)
    chmod 600 "$temp_cache"
    
    # Write header
    echo "# Cached secrets from 1Password CLI" >"$temp_cache"
    echo "# Generated on: "(date) >>"$temp_cache"
    echo "# Format: KEY<tab>ESCAPED_VALUE" >>"$temp_cache"
    echo "" >>"$temp_cache"
    
    # Read from stdin and write escaped entries
    while read -l line
        set -l parts (string split -m 1 \t "$line")

        if test (count $parts) -ge 2
            set -l key $parts[1]
            set -l value $parts[2]
            
            # Escape value safely
            set -l escaped (string escape --style=script -- "$value")
            
            # Write to cache
            printf '%s\t%s\n' "$key" "$escaped" >>"$temp_cache"
        end
    end
    
    # Atomic move with secure permissions
    chmod 600 "$temp_cache"
    mv "$temp_cache" "$cache_file"
    
    return 0
end

#
# Update a single secret in the cache
#
# Updates one secret in the cache file while preserving all others.
# Uses pure Fish operations (no sed).
#
# @param cache_file The path to the cache file
# @param key The secret key to update
# @param value The new value for the secret
# @return 0 on success, 1 on error
#
function _opah_cache_update -d "Update single secret in cache"
    set -l cache_file $argv[1]
    set -l key $argv[2]
    set -l value $argv[3]
    
    if not test -f "$cache_file"
        return 1
    end
    
    # Create temp file
    set -l temp_cache (mktemp)
    chmod 600 "$temp_cache"
    
    set -l escaped (string escape --style=script -- "$value")
    set -l found false
    
    # Read existing cache and update the specific key
    while read -l line
        # Skip empty lines but preserve comments
        if string match -qr '^\s*$' "$line"
            continue
        end
        
        # Check if this is the key we're updating
        if string match -qr "^$key\t" "$line"
            printf '%s\t%s\n' "$key" "$escaped" >>"$temp_cache"
            set found true
        else
            echo "$line" >>"$temp_cache"
        end
    end <"$cache_file"
    
    # If key wasn't found, append it
    if test "$found" = false
        printf '%s\t%s\n' "$key" "$escaped" >>"$temp_cache"
    end
    
    # Atomic move
    chmod 600 "$temp_cache"
    mv "$temp_cache" "$cache_file"
    
    return 0
end

#
# Get list of cached secret keys
#
# Returns a list of all secret keys in the cache file.
#
# @param cache_file The path to the cache file
# @return List of keys (stdout), one per line
#
function _opah_cache_keys -d "Get list of cached secret keys"
    set -l cache_file $argv[1]
    
    if not test -f "$cache_file"
        return 1
    end
    
    while read -l line
        # Skip comments and empty lines
        if string match -qr '^\s*(#|$)' "$line"
            continue
        end
        
        # Extract key (first field before tab, split at most once)
        set -l parts (string split -m 1 \t "$line")
        if test (count $parts) -ge 1
            echo $parts[1]
        end
    end <"$cache_file"
end

#
# Count secrets in cache
#
# Returns the number of secrets stored in the cache file.
#
# @param cache_file The path to the cache file
# @return Number of secrets (stdout)
#
function _opah_cache_count -d "Count secrets in cache"
    set -l cache_file $argv[1]
    
    if not test -f "$cache_file"
        echo 0
        return 0
    end
    
    _opah_cache_keys "$cache_file" | count
end
