function _secrets_show_help -d "Show main help text"
    echo "1Password Secrets Management CLI"
    echo ""
    echo "USAGE:"
    echo "    secrets <SUBCOMMAND> [OPTIONS]"
    echo ""
    echo "SUBCOMMANDS:"
    echo "    status     Show status of cached secrets and configuration"
    echo "    refresh    Refresh secrets from 1Password (with auto-login prompting)"
    echo "    clear      Clear cached secrets and environment variables"
    echo "    config     Show configuration file information and validate format"
    echo "    doctor     Diagnose and validate complete setup"
    echo "    reinit     Re-initialize plugin (useful after authentication changes)"
    echo "    help       Show this help message"
    echo ""
    echo "EXAMPLES:"
    echo "    secrets status              # Show all cached secrets status"
    echo "    secrets status API_KEY      # Show status for specific secret"
    echo "    secrets refresh             # Refresh all secrets from 1Password"
    echo "    secrets refresh DATABASE_URL # Refresh specific secret"
    echo "    secrets clear               # Clear all cached secrets"
    echo "    secrets config              # Show configuration file info"
    echo "    secrets doctor              # Run comprehensive diagnostics"
    echo ""
    echo "For detailed help on a subcommand, use: secrets <SUBCOMMAND> --help"
end